stages:
  - Testes com chrome
  - Testes com firefox


Chrome:
  image: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
  stage: Testes com chrome
  script:
      - npm install --package-lock-only
      - npm install @faker-js/faker --save-dev
      - npm ci  
      - npx cypress run --browser chrome
      
  only:
      refs:
      - pushes 

  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day


Firefox:
  image: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
  stage: Testes com chrome
  script:
      - npm install --package-lock-only
      - npm ci    
      - npx cypress run --browser firefox

  only:
      refs:
      - pushes  

  artifacts:
      when: always
      paths:
        - cypress/videos/**/*.mp4
        - cypress/screenshots/**/*.png
      expire_in: 1 day

